### ISSUE TITLE
Records of Claim doesn't refresh after claim. [10 DAO]

### ISSUE THREAD

**Issue by lychees** [NaoMikuOshi/Matataki-Token-AirDropper#13]
<img width="656" alt="截屏2020-07-04 上午11 55 16" src="https://user-images.githubusercontent.com/2507027/86519185-3dcd8780-bded-11ea-8bf4-5255cd43d52d.png">

Better refresh it.

**Comment by NaoMikuOshi** [comment]
Now it will refresh every minutes automatically
