### ISSUE TITLE
分享红包链接在微信中无法被完整识别

### ISSUE THREAD

**Issue by guanchao71** [NaoMikuOshi/Matataki-Token-AirDropper#14]
![image](https://user-images.githubusercontent.com/10827774/86524946-22c54b00-beb3-11ea-8ba0-11359fef72d5.png)

**Comment by NaoMikuOshi** [comment]
你好，感谢你的反馈。
这应该是微信对 URL 的检测有问题，我会考虑解决方案。

**Comment by NaoMikuOshi** [comment]
fixed
