### ISSUE TITLE
Need to disable the claim button after no airdrops left and error handle when claim fails

### ISSUE THREAD

**Issue by lawvs** [NaoMikuOshi/Matataki-Token-AirDropper#17]
https://github.com/NaoMikuOshi/Matataki-Token-AirDropper/blob/f00ca85527ba0fd3b1feb3c4c8a37f1dea623261/src/pages/Claim.jsx#L121-L126
![image](https://user-images.githubusercontent.com/18554747/86802695-3c7fb180-c0b0-11ea-9f5d-f645ea164a46.png)

```
POST https://api.matataki-airdrop.xyz/airdrop/INITIAL

{"statusCode":400,"message":"Airdrop Amount = 0","error":"Bad Request"}
```

**Comment by NaoMikuOshi** [comment]
Hi,
Thank you for your feedback.
It's my fault that I didn't noticed this. 🧎‍♂️ 
I will fix this problem soon.

**Comment by NaoMikuOshi** [comment]
![image](https://user-images.githubusercontent.com/66997155/86887639-7215b080-c12b-11ea-8c37-b3145350f9fd.png)
Fixed. Thank you again for your feedback.
If you have any troubles encountered, please don't hesitate to raise an issue.😄
