### ISSUE TITLE
希望可以在页面中增加注册引导

### ISSUE THREAD

**Issue by guanchao71** [NaoMikuOshi/Matataki-Token-AirDropper#20]
作为没有使用过Matataki的新用户，或者没有注册过邮箱账号的用户，看到目前的登录界面并不知道应该如何应该去哪里注册账号，或者如何去将我已有账号绑定到邮箱账号上。

**Comment by nekomeowww** [comment]
在 #23 的 [commit 562abcf](https://github.com/nekomeowww/Matataki-Token-AirDropper/commit/562abcf0aab08cd278b48b2a45d5e361862e6091) 添加了这个选项按钮

**Comment by nekomeowww** [comment]
@frankwei98 可以 close issue
