### ISSUE TITLE
希望可以给页脚的Github文字增加跳转链接

### ISSUE THREAD

**Issue by guanchao71** [NaoMikuOshi/Matataki-Token-AirDropper#21]
![image](https://user-images.githubusercontent.com/10827774/87923751-8739fa00-cab0-11ea-843d-8e7e9a81cbc0.png)

**Comment by nekomeowww** [comment]
在 #23 的 [commit e2da0ed](https://github.com/nekomeowww/Matataki-Token-AirDropper/commit/e2da0edc4ae937a24bdcdc6d6e000d718da2d707) 修复了这个问题

**Comment by nekomeowww** [comment]
@frankwei98 可以 close issue
