### ISSUE TITLE
希望可以给用户的头像和名字添加跳转链接。

### ISSUE THREAD

**Issue by lychees** [NaoMikuOshi/Matataki-Token-AirDropper#32]
<img width="663" alt="截屏2020-11-09 下午8 44 17" src="https://user-images.githubusercontent.com/2507027/98542754-57676a00-22cc-11eb-9e56-b497642b012a.png">

好多没头像没名字的账户。。。希望可以单击进去，跳转到用户的页面。。。。

**Comment by Deasoso** [comment]
done.
https://github.com/NaoMikuOshi/Matataki-Token-AirDropper/pull/33
![image](https://user-images.githubusercontent.com/37681734/98656805-0f078500-237c-11eb-8406-712880012cc5.png)
![image](https://user-images.githubusercontent.com/37681734/98656843-1dee3780-237c-11eb-9d13-fc941028133c.png)

**Comment by lychees** [comment]
Solved. https://github.com/NaoMikuOshi/Matataki-Token-AirDropper/commit/41fe97252385c59d3b928bfc4321f09999e41ffa
